### GET request to server
GET http://localhost:8080/api/v1/identity/health

### POST refresh token
POST http://localhost:8080/api/v1/identity/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiUkVGUkVTSF9UT0tFTiIsInN1YiI6ImFiY0BnbWFpbC5jb20iLCJpYXQiOjE3NjUxNzIzOTcsImV4cCI6MTc2NTI1ODc5N30.nCaxn0yDY_DU_oyKxbPD0lHeuYVXOAEfe_2u1CgxregklgpnEE9Praf9xcsyDktaINqprYoiIMorKViYVGbw2TZ9B2Tbvz-PmAj-NSmGE_vGmjst3cbKkUg3ybVB193Ii9LgNXP3IDJ6dLBIbu10ucfeFVjhTPX2RLsSj1Q02LE5Zik8SR1hCU-s5xKJyfmp_xuOg5H1OMc84WcKJVJ87202BUKlZKosn_19ZtLyH0QSGWjptFrtJeN7UMofwEsa3D-t9AuzrfIA0LuQYk7aMHtH81LWEe1F6xfjESK07AGDCoDs8w5c02D1ayhNR64vJRib8yEATsDjcolfp8Fy5g"

}

### POST login
POST http://localhost:8080/api/v1/identity/auth/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "Test123456789@_"
}